# Generated by Django 2.2.7 on 2019-12-14 13:21

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='abstract',
            field=djrichtextfield.models.RichTextField(help_text='help text...', max_length=100000, null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='context',
            field=djrichtextfield.models.RichTextField(help_text='Son histoire, le contexte...', max_length=100000, null=True, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='date',
            field=models.CharField(help_text='help text...', max_length=100000, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='description',
            field=djrichtextfield.models.RichTextField(help_text='help text...', max_length=100000, null=True, verbose_name='Description du produit'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='diagnostic',
            field=djrichtextfield.models.RichTextField(help_text='help text...', max_length=100000, null=True, verbose_name='Diagnostic de la nouveauté'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='produit',
            field=models.CharField(help_text='help text...', max_length=100000, null=True, verbose_name='Le produit '),
        ),
        migrations.AlterField(
            model_name='cases',
            name='reference',
            field=djrichtextfield.models.RichTextField(help_text='help text...', max_length=100000, null=True, verbose_name='Références'),
        ),
    ]
