# Generated by Django 2.2.7 on 2019-12-14 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20191214_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(editable=False)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Cases')),
            ],
        ),
    ]
