# Generated by Django 2.2.7 on 2020-01-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20200129_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='date',
            field=models.CharField(max_length=100000, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_subject', to='stories.Subject', verbose_name='Subject'),
        ),
    ]
