# Generated by Django 2.2.7 on 2020-01-29 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20200129_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='abstract',
            field=djrichtextfield.models.RichTextField(max_length=100000, null=True, verbose_name='Abstract '),
        ),
        migrations.AlterField(
            model_name='cases',
            name='auteur',
            field=models.CharField(max_length=200, null=True, verbose_name='The author(s)'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='context',
            field=djrichtextfield.models.RichTextField(help_text='Son histoire, le contexte...', max_length=100000, null=True, verbose_name='Context : '),
        ),
        migrations.AlterField(
            model_name='cases',
            name='context_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Figure associated with the context'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='The date of creation :'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='date',
            field=models.CharField(max_length=100000, null=True, verbose_name='Date '),
        ),
        migrations.AlterField(
            model_name='cases',
            name='description',
            field=djrichtextfield.models.RichTextField(max_length=100000, null=True, verbose_name='Product description : '),
        ),
        migrations.AlterField(
            model_name='cases',
            name='description_shema',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Figure associated with the description'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='diagnostic',
            field=djrichtextfield.models.RichTextField(max_length=100000, null=True, verbose_name='Diagnosis of novelty : '),
        ),
        migrations.AlterField(
            model_name='cases',
            name='diagnostic_shema',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Figure associated with the diagnosis of novelty : '),
        ),
        migrations.AlterField(
            model_name='cases',
            name='image_produit',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Figure associated with the product '),
        ),
        migrations.AlterField(
            model_name='cases',
            name='processus',
            field=djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='Description of the innovation process :'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='processus_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Process-title '),
        ),
        migrations.AlterField(
            model_name='cases',
            name='processus_shema',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Figure associated with the description of the innovation process : '),
        ),
        migrations.AlterField(
            model_name='cases',
            name='produit',
            field=models.CharField(max_length=100000, null=True, verbose_name='Product :  '),
        ),
        migrations.AlterField(
            model_name='cases',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='The date of publication'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='reference',
            field=djrichtextfield.models.RichTextField(max_length=100000, null=True, verbose_name='References '),
        ),
        migrations.AlterField(
            model_name='cases',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_subject', to='stories.Subject', verbose_name='Subject : '),
        ),
        migrations.AlterField(
            model_name='cases',
            name='title_case',
            field=models.CharField(blank=True, help_text='Make your title attention-grabbing and informative.', max_length=255, null=True, verbose_name='Your case name  : '),
        ),
    ]
