# Generated by Django 2.2.7 on 2020-01-29 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20200129_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='mois',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_mois', to='stories.Mois', verbose_name='Month'),
        ),
    ]
