# Generated by Django 2.2.7 on 2020-02-06 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20200129_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_publ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='The publication date  ')),
                ('case_publ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases_public', to='stories.Cases')),
            ],
        ),
    ]
